### ISSUE TITLE
TwilioVoice can not hear voice

### ISSUE THREAD

**Issue by Juweloma** [twilio/voice-quickstart-ios#107]
Hello, 
I built an iOS App with the TwilioVoice 2.0.1 
The TwilioVoice works always good until today I received the following error:

**PJSIP(1):    pjsua_aud.c  .Unable to open sound device: Unknown OpenSSL error 503317117 [status=506637]
[DEBUG Twilio] Inside on_call_state(), call: 0x1c012a8c0, internal state: 4
[VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_CONFIRMED
[VERBOSE TVOCall] handlePJSIPInviteStateConfirmed. Error: (null)
callDidConnect:
[VERBOSE Twilio] on_call_tsx_state(), state: 6, status_code: 200: OK
[VERBOSE Twilio] Inside on_rx_response(): received INVITE response, rewriting contact
[ERROR TwilioVoice] Failed to activate the audio device. Please contact support with a verbose SDK log if you repeatedly encounter this error.**

After that the App can successfully with another telephone connect. But in the App I cannot hear any voice. I tried to delete the app and install again. But nothing changes.
What should I do to solve this issue? Please help me!

**Comment by Juweloma** [comment]
I solved this problem by adding 
**try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord)**
in func routeAudioToSpeaker ()

**Comment by idelgado** [comment]
We have not been able to reliably reproduce this issue. Can you provide information about the device/OS level that you are using? Also, are there any apps that are using the audio device when you attempt the call? Is this while using CallKit?

**Comment by bchen-twilio** [comment]
Hi @Juweloma 

How are things? We haven't heard back from you about the issue but we would still like to check if you are still experiencing the audio issue?
We've been trying on iOS 11 and 10 but so far as @idelgado mentioned we are still not able to reproduce the issue with 2.0.1. It would be great to have more details about the environments where you are seeing this issue.

Thanks
-bobie

**Comment by mmokona** [comment]
Hello.
At some point, I began to receive this issue constantly.  
Environments: 
1) TwilioVoice 2.0.1 (updated with 2.0.0-beta19), without CallKit
2) Server: twilio-php 5.16.6 (updated with 5.16.0)
3) Devices: Iphone 6 10.3.3, Iphone SE 11.0, Iphone X 11.2.6
4) Language: ObjectiveC
5) Xcode 9.2, linker flag -ObjC, target ios version: 9.0

Logs:
```
2018-03-21 15:05:47.753728+0700 testapp[249:20997] AVAudioSession Permission granted
2018-03-21 15:05:48.061749+0700 testapp[249:20997] [VERBOSE TwilioVoice] Registering for Twilio push notifications
Access Token:	eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzk1MjJjNWNiYzIyYTZiMWExZjFjMzEyMmVmMTg1NWRlLTE1MjE2MTk1NDciLCJpc3MiOiJTSzk1MjJjNWNiYzIyYTZiMWExZjFjMzEyMmVmMTg1NWRlIiwic3ViIjoiQUNjNDFjODEwZjMxYjlkNDA0NTRhYzUwNjk2ZmI3ODkxZSIsImV4cCI6MTUyMTcwNTk0NywiZ3JhbnRzIjp7ImlkZW50aXR5IjoiNWQ3NThjNmZiY2VhNDBhNmI0N2JhNmEzYjI5ZjZhMGQiLCJ2b2ljZSI6eyJvdXRnb2luZyI6eyJhcHBsaWNhdGlvbl9zaWQiOiJBUGZlNmM5NGNmNjE2NjllNjczMDU0Y2MwYTc2M2IwYWI0In0sInB1c2hfY3JlZGVudGlhbF9zaWQiOiJDUmIxMjg5M2IwOWFhODI3NTg5NjQyNTQxMGYyNjdhMWFiIn19fQ.BacF98ki1_atW-1NFccYU18Pdik35vcTlt6Nufk-92k
VoIP Registry Token:	<af39b511 f3b5b411 1f34012c 32259915 8e9b2788 7cf7c764 bbfb78e0 9b1188c7>
2018-03-21 15:05:48.062921+0700 testapp[249:20997] [DEBUG TVONotificationClient] Register for push notifications.
2018-03-21 15:05:49.309766+0700 testapp[249:21054] [DEBUG TVONotificationClient] Completed registration request.
2018-03-21 15:05:49.310363+0700 testapp[249:20997] [INFO TwilioVoice] Inside register:deviceToken:completion:, registered for Twilio push notifications.
2018-03-21 15:05:49.310475+0700 testapp[249:20997] Successfully registered for VoIP push notifications.
2018-03-21 15:06:04.511167+0700 testapp[249:20997] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/16000/1 -> priority: 255
2018-03-21 15:06:04.511410+0700 testapp[249:20997] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/8000/1 -> priority: 254
2018-03-21 15:06:04.511705+0700 testapp[249:20997] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/32000/1 -> priority: 0
2018-03-21 15:06:04.511868+0700 testapp[249:20997] [VERBOSE Twilio] Inside setCodecPriorities:, codec: PCMU/8000/1 -> priority: 128
2018-03-21 15:06:04.512137+0700 testapp[249:20997] [VERBOSE Twilio] Inside setCodecPriorities:, codec: PCMA/8000/1 -> priority: 0
2018-03-21 15:06:04.513187+0700 testapp[249:20997] [INFO Twilio] recreateMainTransport, Found valid IPv4 address: 192.168.1.36
2018-03-21 15:06:04.513741+0700 testapp[249:20997] [DEBUG TVOConstants] X-Twilio-Client string: {"p":"ios","v":"2.0.1","mobile":{"arch":"arm64","product":"iPhone","name":"iPhone7,2","v":"10.3.3"}}, inside TVOConstants clientString
2018-03-21 15:06:04.516110+0700 testapp[249:20997] [DEBUG TVOReachability] Reachability Flag Status: -R ------- networkStatusForFlags
2018-03-21 15:06:04.516363+0700 testapp[249:20997] [DEBUG TVOCommandHandler] Inside postCommand:, received command of type TVOMakeCallCommand
2018-03-21 15:06:04.516650+0700 testapp[249:21052] [VERBOSE Twilio] Inside constructUri: Registration URL: sip:None@chunderm.gll.twilio.com;transport=tls
2018-03-21 15:06:04.516778+0700 testapp[249:21052] [INFO TVOMakeCallCommand] Call URI: sip:None@chunderm.gll.twilio.com;transport=tls
2018-03-21 15:06:04.517118+0700 testapp[249:21052] [VERBOSE TVOCallImpl] Inside makeCall, record permission was granted
2018-03-21 15:06:04.520530+0700 testapp[249:21052] [DEBUG Twilio] Inside on_call_state(), call: 0x174127800, internal state: 1
2018-03-21 15:06:04.520637+0700 testapp[249:21052] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_CALLING
2018-03-21 15:06:04.520779+0700 testapp[249:21052] [VERBOSE TVOCall] handlePJSIPInviteStateCalling. Error: (null)
2018-03-21 15:06:04.520948+0700 testapp[249:21052] [VERBOSE Twilio] on_call_tsx_state(), state: 1, status_code: 0: (null)
2018-03-21 15:06:05.046895+0700 testapp[249:21153] [DEBUG Twilio] on_transport_state(): 0
2018-03-21 15:06:05.047233+0700 testapp[249:21153] [DEBUG Twilio] ------>Transport connected: 0x21a7c28, inside transportConnected:
2018-03-21 15:06:05.148153+0700 testapp[249:21153] [VERBOSE Twilio] Inside on_rx_response(): received INVITE response, rewriting contact
2018-03-21 15:06:05.149100+0700 testapp[249:21153] [DEBUG Twilio] In on_call_redirected, call_id: 0, target: 0x104f058f8, pjsip_event: 0x16e404668
2018-03-21 15:06:05.151873+0700 testapp[249:21153] [VERBOSE Twilio] on_call_tsx_state(), state: 1, status_code: 0: (null)
2018-03-21 15:06:05.152193+0700 testapp[249:21153] [VERBOSE Twilio] on_call_tsx_state(), state: 4, status_code: 302: Moved Temporarily
2018-03-21 15:06:05.152637+0700 testapp[249:21153] [VERBOSE Twilio] on_call_tsx_state(), state: 6, status_code: 302: Moved Temporarily
2018-03-21 15:06:05.153160+0700 testapp[249:21153] [DEBUG Twilio] ------>Destroying transport: 0x1021a7c28, inside releaseTransport
2018-03-21 15:06:06.171471+0700 testapp[249:21153] [DEBUG Twilio] on_transport_state(): 0
2018-03-21 15:06:06.171955+0700 testapp[249:21153] [DEBUG Twilio] ------>Transport connected: 0x1180c28, inside transportConnected:
2018-03-21 15:06:06.480191+0700 testapp[249:21153] [VERBOSE Twilio] Inside on_rx_response(): received INVITE response, rewriting contact
2018-03-21 15:06:06.480614+0700 testapp[249:21153] [WARN Twilio]  .. cannot rewrite contact -> no contact
2018-03-21 15:06:06.482198+0700 testapp[249:21153] [VERBOSE Twilio] on_call_tsx_state(), state: 3, status_code: 100: Trying
2018-03-21 15:06:06.774711+0700 testapp[249:21153] [VERBOSE Twilio] Inside on_rx_response(): received INVITE response, rewriting contact
2018-03-21 15:06:06.775259+0700 testapp[249:21153] [DEBUG Twilio] Inside on_call_state(), call: 0x174127800, internal state: 2
2018-03-21 15:06:06.775449+0700 testapp[249:21153] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_EARLY
2018-03-21 15:06:06.775671+0700 testapp[249:21153] [VERBOSE TVOCall] handlePJSIPInviteStateEarly. Error: (null)
2018-03-21 15:06:06.775891+0700 testapp[249:21153] [VERBOSE Twilio] on_call_tsx_state(), state: 3, status_code: 180: Ringing
2018-03-21 15:06:07.156792+0700 testapp[249:21153] [VERBOSE Twilio] Inside on_rx_response(): received INVITE response, rewriting contact
2018-03-21 15:06:07.157476+0700 testapp[249:21153] [DEBUG Twilio] Inside on_call_state(), call: 0x174127800, internal state: 3
2018-03-21 15:06:07.158109+0700 testapp[249:21153] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_CONNECTING
2018-03-21 15:06:07.158741+0700 testapp[249:21153] [VERBOSE TVOCall] handlePJSIPInviteStateConnecting. Error: (null)
2018-03-21 15:06:07.392045+0700 testapp[249:21052] [aurioc] 1322: AUIOClient_StartIO failed (-66637)
2018-03-21 15:06:07.486472+0700 testapp[249:21052] [aurioc] 1322: AUIOClient_StartIO failed (-66637)
2018-03-21 15:06:07.596223+0700 testapp[249:21052] [aurioc] 1322: AUIOClient_StartIO failed (-66637)
2018-03-21 15:06:07.688193+0700 testapp[249:21052] [aurioc] 1322: AUIOClient_StartIO failed (-66637)
2018-03-21 15:06:07.757404+0700 testapp[249:21052] [aurioc] 1322: AUIOClient_StartIO failed (-66637)
2018-03-21 15:06:07.827941+0700 testapp[249:21052] [aurioc] 1322: AUIOClient_StartIO failed (-66637)
2018-03-21 15:06:07.835265+0700 testapp[249:21052] PJSIP(1):    pjsua_aud.c  .Unable to open sound device: Unknown OpenSSL error 503317117 [status=506637]
2018-03-21 15:06:07.836683+0700 testapp[249:21153] [DEBUG Twilio] Inside on_call_state(), call: 0x174127800, internal state: 4
2018-03-21 15:06:07.836839+0700 testapp[249:21153] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_CONFIRMED
2018-03-21 15:06:07.836971+0700 testapp[249:21153] [VERBOSE TVOCall] handlePJSIPInviteStateConfirmed. Error: (null)
2018-03-21 15:06:07.837596+0700 testapp[249:20997] callDidConnect:
2018-03-21 15:06:07.841249+0700 testapp[249:21153] [VERBOSE Twilio] on_call_tsx_state(), state: 6, status_code: 200: OK
2018-03-21 15:06:07.843071+0700 testapp[249:21153] [VERBOSE Twilio] Inside on_rx_response(): received INVITE response, rewriting contact
2018-03-21 15:06:07.847068+0700 testapp[249:21052] [ERROR TwilioVoice] Failed to activate the audio device. Please contact support with a verbose SDK log if you repeatedly encounter this error.
2018-03-21 15:06:07.851359+0700 testapp[249:21052] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA90d6e10773b9694b4532ea5bbbf2dee0;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-21T15:06:07.848+07:00";
    "timestamp_ms" = 1521619567848;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-21 15:06:08.844659+0700 testapp[249:21052] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA90d6e10773b9694b4532ea5bbbf2dee0;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-21T15:06:08.842+07:00";
    "timestamp_ms" = 1521619568842;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-21 15:06:09.856230+0700 testapp[249:21053] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA90d6e10773b9694b4532ea5bbbf2dee0;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-21T15:06:09.854+07:00";
    "timestamp_ms" = 1521619569854;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-21 15:06:10.006554+0700 testapp[249:20997] [DEBUG TVOCommandHandler] Inside postCommand:, received command of type TVOHangupCallCommand
2018-03-21 15:06:10.006964+0700 testapp[249:21052] [DEBUG TVOCallImpl] Inside TVOCallImpl.hangup, hanging up call, callID: 0
2018-03-21 15:06:10.006989+0700 testapp[249:20997] [INFO TVOCall] Inside publishConnectionEvent:, event type: disconnected-by-local
2018-03-21 15:06:10.008805+0700 testapp[249:21052] [VERBOSE Twilio] on_call_tsx_state(), state: 1, status_code: 0: (null)
2018-03-21 15:06:10.009240+0700 testapp[249:20997] [VERBOSE TVOCall] Inside publisherConnectionEvent:, sending disconnected-by-local event
2018-03-21 15:06:10.388748+0700 testapp[249:21153] [VERBOSE Twilio] on_call_tsx_state(), state: 4, status_code: 200: OK
2018-03-21 15:06:10.389057+0700 testapp[249:21153] [DEBUG Twilio] Inside on_call_state(), call: 0x174127800, internal state: 6
2018-03-21 15:06:10.389255+0700 testapp[249:21153] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_DISCONNECTED, internal state: 6, last_status: 200
2018-03-21 15:06:10.389447+0700 testapp[249:21153] [VERBOSE TVOCall] handlePJSIPInviteStateDisconnected. Error: (null)
2018-03-21 15:06:10.392392+0700 testapp[249:20997] Call disconnected
2018-03-21 15:06:10.394449+0700 testapp[249:21193] [DEBUG TwilioVoice] Inside removeFromActiveCalls:, remove call <TVOCall: 0x174127800> from active calls
2018-03-21 15:06:10.395125+0700 testapp[249:21193] [DEBUG Twilio] dealloc Twilio.
2018-03-21 15:06:10.395886+0700 testapp[249:21193] [DEBUG Twilio] ------>Destroying transport: 0x101180c28, inside releaseAllTransports
2018-03-21 15:06:10.396247+0700 testapp[249:21193] [DEBUG Twilio] on_transport_state(): 2
2018-03-21 15:06:10.405445+0700 testapp[249:20997] Failed to route audio to speaker: Не удалось завершить операцию. (OSStatus, ошибка -50)
2018-03-21 15:06:10.912529+0700 testapp[249:21193] [DEBUG TVOCall] dealloc.

```

**Comment by bchen-twilio** [comment]
Hi @mmokona 

There are couple of known issues related to call audio and stability in the last few versions of beta and we have fixed them in the GA version. Please update to the latest (2.0.3).

Thanks.
-bobie

**Comment by mmokona** [comment]
Hello @bchen-twilio 
Thanks for the answer. I updated TwilioVoice to version 2.0.3, but issue still here.
```
2018-03-22 14:41:50.088490+0700 testapp[330:120686] AVAudioSession Permission granted
2018-03-22 14:41:50.431721+0700 testapp[330:120686] [VERBOSE TwilioVoice] Registering for Twilio push notifications
Access Token:   eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzk1MjJjNWNiYzIyYTZiMWExZjFjMzEyMmVmMTg1NWRlLTE1MjE3MDQ1MTAiLCJpc3MiOiJTSzk1MjJjNWNiYzIyYTZiMWExZjFjMzEyMmVmMTg1NWRlIiwic3ViIjoiQUNjNDFjODEwZjMxYjlkNDA0NTRhYzUwNjk2ZmI3ODkxZSIsImV4cCI6MTUyMTc5MDkxMCwiZ3JhbnRzIjp7ImlkZW50aXR5IjoiNWQ3NThjNmZiY2VhNDBhNmI0N2JhNmEzYjI5ZjZhMGQiLCJ2b2ljZSI6eyJvdXRnb2luZyI6eyJhcHBsaWNhdGlvbl9zaWQiOiJBUGZlNmM5NGNmNjE2NjllNjczMDU0Y2MwYTc2M2IwYWI0In0sInB1c2hfY3JlZGVudGlhbF9zaWQiOiJDUmIxMjg5M2IwOWFhODI3NTg5NjQyNTQxMGYyNjdhMWFiIn19fQ.8QrO9yr0HZgmr0qmx-9I4x-Szuuy-fr-_86vg8GcdZs
VoIP Registry Token:    <af39b511 f3b5b411 1f34012c 32259915 8e9b2788 7cf7c764 bbfb78e0 9b1188c7>
2018-03-22 14:41:50.432297+0700 testapp[330:120686] [DEBUG TVONotificationClient] Register for push notifications.
2018-03-22 14:41:51.651435+0700 testapp[330:120731] [DEBUG TVONotificationClient] Completed registration request.
2018-03-22 14:41:51.797621+0700 testapp[330:120686] [INFO TwilioVoice] Inside register:deviceToken:completion:, registered for Twilio push notifications.
2018-03-22 14:41:51.797814+0700 testapp[330:120686] Successfully registered for VoIP push notifications.
2018-03-22 14:41:58.757690+0700 testapp[330:120686] [DEBUG Twilio] init Twilio user agent.
WARNING: no real random source present!
2018-03-22 14:41:58.882577+0700 testapp[330:120686] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/16000/1 -> priority: 255
2018-03-22 14:41:58.882968+0700 testapp[330:120686] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/8000/1 -> priority: 254
2018-03-22 14:41:58.883204+0700 testapp[330:120686] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/32000/1 -> priority: 0
2018-03-22 14:41:58.883634+0700 testapp[330:120686] [VERBOSE Twilio] Inside setCodecPriorities:, codec: PCMU/8000/1 -> priority: 128
2018-03-22 14:41:58.883867+0700 testapp[330:120686] [VERBOSE Twilio] Inside setCodecPriorities:, codec: PCMA/8000/1 -> priority: 0
2018-03-22 14:41:58.885442+0700 testapp[330:120686] [INFO Twilio] recreateMainTransport, Found valid IPv4 address: 192.168.1.36
2018-03-22 14:41:58.886978+0700 testapp[330:120686] [DEBUG TVOConstants] X-Twilio-Client string: {"p":"ios","v":"2.0.3","mobile":{"arch":"arm64","product":"iPhone","name":"iPhone7,2","v":"10.3.3"}}, inside TVOConstants clientString
2018-03-22 14:41:58.891109+0700 testapp[330:120686] [DEBUG TVOReachability] Reachability Flag Status: -R ------- networkStatusForFlags
2018-03-22 14:41:58.891462+0700 testapp[330:120686] [DEBUG TVOCommandHandler] Inside postCommand:, received command of type TVOMakeCallCommand
2018-03-22 14:41:58.892111+0700 testapp[330:120734] [VERBOSE Twilio] Inside constructUri: Registration URL: sip:None@chunderm.gll.twilio.com;transport=tls
2018-03-22 14:41:58.892354+0700 testapp[330:120734] [INFO TVOMakeCallCommand] Call URI: sip:None@chunderm.gll.twilio.com;transport=tls
2018-03-22 14:41:58.893636+0700 testapp[330:120734] [VERBOSE TVOCallImpl] Inside makeCall, record permission was granted
2018-03-22 14:41:58.902511+0700 testapp[330:120734] [DEBUG Twilio] Inside on_call_state(), call: 0x174129e20, internal state: 1
2018-03-22 14:41:58.902742+0700 testapp[330:120734] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_CALLING
2018-03-22 14:41:58.902963+0700 testapp[330:120734] [VERBOSE TVOCall] handlePJSIPInviteStateCalling. Error: (null)
2018-03-22 14:41:58.903167+0700 testapp[330:120734] [VERBOSE Twilio] on_call_tsx_state(), state: 1, status_code: 0: (null)
2018-03-22 14:42:00.170915+0700 testapp[330:120828] [DEBUG Twilio] on_transport_state(): 0
2018-03-22 14:42:00.171333+0700 testapp[330:120828] [DEBUG Twilio] ------>Transport connected: 0x4213c428, inside transportConnected:
2018-03-22 14:42:00.279463+0700 testapp[330:120828] [VERBOSE Twilio] Inside on_rx_response(): received INVITE response, rewriting contact
2018-03-22 14:42:00.280449+0700 testapp[330:120828] [DEBUG Twilio] In on_call_redirected, call_id: 0, target: 0x141ecbf78, pjsip_event: 0x16e4cc668
2018-03-22 14:42:00.281924+0700 testapp[330:120828] [VERBOSE Twilio] on_call_tsx_state(), state: 1, status_code: 0: (null)
2018-03-22 14:42:00.282167+0700 testapp[330:120828] [VERBOSE Twilio] on_call_tsx_state(), state: 4, status_code: 302: Moved Temporarily
2018-03-22 14:42:00.282544+0700 testapp[330:120828] [VERBOSE Twilio] on_call_tsx_state(), state: 6, status_code: 302: Moved Temporarily
2018-03-22 14:42:00.282843+0700 testapp[330:120828] [DEBUG Twilio] ------>Destroying transport: 0x14213c428, inside releaseTransport
2018-03-22 14:42:00.955748+0700 testapp[330:120828] [DEBUG Twilio] on_transport_state(): 0
2018-03-22 14:42:00.956109+0700 testapp[330:120828] [DEBUG Twilio] ------>Transport connected: 0x4214c028, inside transportConnected:
2018-03-22 14:42:01.312257+0700 testapp[330:120828] [VERBOSE Twilio] Inside on_rx_response(): received INVITE response, rewriting contact
2018-03-22 14:42:01.312612+0700 testapp[330:120828] [WARN Twilio]  .. cannot rewrite contact -> no contact
2018-03-22 14:42:01.312921+0700 testapp[330:120828] [VERBOSE Twilio] on_call_tsx_state(), state: 3, status_code: 100: Trying
2018-03-22 14:42:01.407623+0700 testapp[330:120828] [VERBOSE Twilio] Inside on_rx_response(): received INVITE response, rewriting contact
2018-03-22 14:42:01.408184+0700 testapp[330:120828] [DEBUG Twilio] Inside on_call_state(), call: 0x174129e20, internal state: 2
2018-03-22 14:42:01.408373+0700 testapp[330:120828] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_EARLY
2018-03-22 14:42:01.408568+0700 testapp[330:120828] [VERBOSE TVOCall] handlePJSIPInviteStateEarly. Error: (null)
2018-03-22 14:42:01.408782+0700 testapp[330:120828] [VERBOSE Twilio] on_call_tsx_state(), state: 3, status_code: 180: Ringing
2018-03-22 14:42:01.593231+0700 testapp[330:120828] [VERBOSE Twilio] Inside on_rx_response(): received INVITE response, rewriting contact
2018-03-22 14:42:01.593747+0700 testapp[330:120828] [DEBUG Twilio] Inside on_call_state(), call: 0x174129e20, internal state: 3
2018-03-22 14:42:01.593936+0700 testapp[330:120828] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_CONNECTING
2018-03-22 14:42:01.594122+0700 testapp[330:120828] [VERBOSE TVOCall] handlePJSIPInviteStateConnecting. Error: (null)
2018-03-22 14:42:01.823510+0700 testapp[330:120734] [aurioc] 1322: AUIOClient_StartIO failed (-66637)
2018-03-22 14:42:01.940910+0700 testapp[330:120734] [aurioc] 1322: AUIOClient_StartIO failed (-66637)
2018-03-22 14:42:02.028119+0700 testapp[330:120734] [aurioc] 1322: AUIOClient_StartIO failed (-66637)
2018-03-22 14:42:02.119729+0700 testapp[330:120734] [aurioc] 1322: AUIOClient_StartIO failed (-66637)
2018-03-22 14:42:02.190365+0700 testapp[330:120734] [aurioc] 1322: AUIOClient_StartIO failed (-66637)
2018-03-22 14:42:02.258936+0700 testapp[330:120734] [aurioc] 1322: AUIOClient_StartIO failed (-66637)
2018-03-22 14:42:02.266406+0700 testapp[330:120734] PJSIP(1):    pjsua_aud.c  .Unable to open sound device: Unknown OpenSSL error 503317117 [status=506637]
2018-03-22 14:42:02.266585+0700 testapp[330:120734] [ERROR TwilioVoice] Failed to activate the audio device. Please contact support with a verbose SDK log if you repeatedly encounter this error.
2018-03-22 14:42:02.266722+0700 testapp[330:120734] [VERBOSE Twilio] Active ports before pjsua_conf_connect(): 2
2018-03-22 14:42:02.267112+0700 testapp[330:120828] [DEBUG Twilio] Inside on_call_state(), call: 0x174129e20, internal state: 4
2018-03-22 14:42:02.273023+0700 testapp[330:120828] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_CONFIRMED
2018-03-22 14:42:02.274399+0700 testapp[330:120828] [VERBOSE TVOCall] handlePJSIPInviteStateConfirmed. Error: (null)
2018-03-22 14:42:02.274948+0700 testapp[330:120686] callDidConnect:
2018-03-22 14:42:02.275209+0700 testapp[330:120828] [VERBOSE Twilio] on_call_tsx_state(), state: 6, status_code: 200: OK
2018-03-22 14:42:02.275546+0700 testapp[330:120734] [VERBOSE Twilio] Active ports after pjsua_conf_connect(): 2
2018-03-22 14:42:02.278053+0700 testapp[330:120828] [VERBOSE Twilio] Inside on_rx_response(): received INVITE response, rewriting contact
2018-03-22 14:42:02.282021+0700 testapp[330:120734] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:02.278+07:00";
    "timestamp_ms" = 1521704522277;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:03.280932+0700 testapp[330:120734] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:03.279+07:00";
    "timestamp_ms" = 1521704523278;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:04.281105+0700 testapp[330:120734] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:04.279+07:00";
    "timestamp_ms" = 1521704524278;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:05.281204+0700 testapp[330:120731] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:05.279+07:00";
    "timestamp_ms" = 1521704525279;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:06.281240+0700 testapp[330:120734] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:06.279+07:00";
    "timestamp_ms" = 1521704526279;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:07.280694+0700 testapp[330:120734] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:07.279+07:00";
    "timestamp_ms" = 1521704527278;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:08.280911+0700 testapp[330:120731] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:08.279+07:00";
    "timestamp_ms" = 1521704528278;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:09.280555+0700 testapp[330:120731] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:09.279+07:00";
    "timestamp_ms" = 1521704529278;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:10.281110+0700 testapp[330:120732] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:10.279+07:00";
    "timestamp_ms" = 1521704530279;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:11.280316+0700 testapp[330:120732] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:11.278+07:00";
    "timestamp_ms" = 1521704531278;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:12.281195+0700 testapp[330:120731] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:12.279+07:00";
    "timestamp_ms" = 1521704532279;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:13.281179+0700 testapp[330:120732] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:13.279+07:00";
    "timestamp_ms" = 1521704533279;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:14.281035+0700 testapp[330:120734] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:14.279+07:00";
    "timestamp_ms" = 1521704534279;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:15.281068+0700 testapp[330:120734] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:15.279+07:00";
    "timestamp_ms" = 1521704535279;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:16.281085+0700 testapp[330:120734] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:16.279+07:00";
    "timestamp_ms" = 1521704536279;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:17.281104+0700 testapp[330:120734] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:17.279+07:00";
    "timestamp_ms" = 1521704537279;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:18.280870+0700 testapp[330:120734] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:18.279+07:00";
    "timestamp_ms" = 1521704538278;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:19.281066+0700 testapp[330:120731] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:19.279+07:00";
    "timestamp_ms" = 1521704539279;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:19.760336+0700 testapp[330:120686] [DEBUG TVOCommandHandler] Inside postCommand:, received command of type TVOHangupCallCommand
2018-03-22 14:42:19.760747+0700 testapp[330:120731] [DEBUG TVOCallImpl] Inside TVOCallImpl.hangup, hanging up call, callID: 0
2018-03-22 14:42:19.760786+0700 testapp[330:120686] [INFO TVOCall] Inside publishConnectionEvent:, event type: disconnected-by-local
2018-03-22 14:42:19.762171+0700 testapp[330:120731] [VERBOSE Twilio] on_call_tsx_state(), state: 1, status_code: 0: (null)
2018-03-22 14:42:19.762427+0700 testapp[330:120686] [VERBOSE TVOCall] Inside publisherConnectionEvent:, sending disconnected-by-local event
2018-03-22 14:42:20.280797+0700 testapp[330:120733] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA7eb49127161858267cb5f4213af6c6cb;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-03-22T14:42:20.279+07:00";
    "timestamp_ms" = 1521704540278;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2018-03-22 14:42:20.370989+0700 testapp[330:120828] [VERBOSE Twilio] on_call_tsx_state(), state: 4, status_code: 200: OK
2018-03-22 14:42:20.371301+0700 testapp[330:120828] [DEBUG Twilio] Inside on_call_state(), call: 0x174129e20, internal state: 6
2018-03-22 14:42:20.371652+0700 testapp[330:120828] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_DISCONNECTED, internal state: 6, last_status: 200
2018-03-22 14:42:20.371848+0700 testapp[330:120828] [VERBOSE TVOCall] handlePJSIPInviteStateDisconnected. Error: (null)
2018-03-22 14:42:20.375309+0700 testapp[330:120686] Call disconnected
2018-03-22 14:42:20.387231+0700 testapp[330:120686] Failed to route audio to speaker: Не удалось завершить операцию. (OSStatus, ошибка -50)
2018-03-22 14:42:20.388510+0700 testapp[330:120734] [DEBUG TwilioVoice] Inside removeFromActiveCalls:, remove call <TVOCall: 0x174129e20> from active calls
2018-03-22 14:42:20.388779+0700 testapp[330:120734] [DEBUG Twilio] dealloc Twilio.
2018-03-22 14:42:20.404672+0700 testapp[330:120734] [DEBUG Twilio] ------>Destroying transport: 0x14214c028, inside releaseAllTransports
2018-03-22 14:42:20.404928+0700 testapp[330:120734] [DEBUG Twilio] on_transport_state(): 2
2018-03-22 14:42:20.909856+0700 testapp[330:120734] [DEBUG TVOCall] dealloc.
```
I could not find the significant difference between the two logs

**Comment by bchen-twilio** [comment]
Hi @mmokona 

Thanks for updating to the latest SDK and providing the log.
From the log I cannot find the trace of `TwilioVoice.audioEnabled` being set. This API is added in the last few versions of beta and available in the official GA version. Please take a look at the `ViewController.m` of the quickstart and make sure you configure the `TwilioVoice.audioEnabled` flag when necessary.

-bobie

**Comment by mmokona** [comment]
Ok, i found my mistake.
In `[ViewController placeCall:]` i change code to this:
```
_call = [TwilioVoice call:[self fetchAccessToken]
                                         params:@{kTwimlParamTo: self.outgoingValue.text}
                                       delegate:strongSelf];
[self playOutgoingRingtone:nil];
``` 
Returning the code back everything fixed. Thanks for help.

**Comment by devlove1C** [comment]
**Hello @bchen-twilio , 
I am getting the issue in twilio voip call. Actually i am using twilio for voip call, it's working fine but when I am receiving first call at any device, voice is not audible. After first call its working fine
The twilio object after Receive the first call :** 

```
Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" ="callSidIDXYZ";
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2019-02-09T19:20:02.048+05:30";
    "timestamp_ms" = 1549720202048;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
```
* TwilioVoice 2.7.0 with  CallKit
* Server: twilio-php 5.16.6 (updated with 5.16.0)
* Devices: Iphone X (iOS Version 12+)
* Language: SWift 4.0

Why **audio_level_out** value is zero- zero at first time. 
Thanks

**Comment by outlookamusements** [comment]
**Hello @bchen-twilio , 
I’m getting issue for VOIP call confirmation voice. Many time we tried to call for confirmation voice is not audible at first time(When user is receiving first call for confirmation it’s not audible, after first call its working fine) and user get stuck for confirmation.
We’ve tried and found "handleCallInviteReceived" method return “ "audio_level_out" = 0” in  this case voice is not audible. When  “audio_level_out ” return greater then 0 then voice audible.
Please suggest to me, how to solve this issue.:** 

I’m using below SDK :
* TwilioVoice 2.7.0 with  CallKit
* Server: twilio-php 5.16.6 (updated with 5.16.0)
* Devices: Iphone X (iOS Version 12+)
* Language: SWift 4.0 

**handle call recivce below object details** 
```
Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" ="callSidIDXYZ";
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2019-02-09T19:20:02.048+05:30";
    "timestamp_ms" = 1549720202048;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
```

Thanks

**Comment by bchen-twilio** [comment]
Hi @outlookamusements 

There is a bug in the 2.0 iOS SDK which will occasionally cause the underlying audio unit not being started properly, especially when integrated with CallKit. Would you consider using the 3.0 Voice SDK? It's currently in the beta phase but has proven the robustness of the media connection.
The [3.x branch](https://github.com/twilio/voice-quickstart-swift/tree/3.x) of the Swift quickstart and the [migration guide](https://github.com/twilio/voice-quickstart-swift/tree/3.x#migration-guide) should help you update your app with 3.0 APIs.

-bobie

**Comment by outlookamusements** [comment]
Hello @bchen-twilio 
I have used the [3.x branch](https://github.com/twilio/voice-quickstart-swift/tree/3.x). Its resolved the issue, But voice is audible after 8-15 second every time.
Please suggest me how to resolve this problem.

My Code for Accept the call and on LoudSpeaker :
```
func provider(_ provider: CXProvider, perform action: CXAnswerCallAction) {
    NSLog("provider:performAnswerCallAction:")
    assert(action.callUUID == self.callInvite?.uuid)
    audioDevice.isEnabled = false
    audioDevice.block()
    self.performAnswerVoiceCall(uuid: action.callUUID) { (success) in
        if (success) {
            action.fulfill()
            do {
                try AVAudioSession.sharedInstance().overrideOutputAudioPort(.speaker)
            } catch {
                NSLog(error.localizedDescription)
            }
        } else {
            action.fail()
        }
    }
}

```

Thanks

**Comment by bchen-twilio** [comment]
Hi @outlookamusements 

Thanks for trying out the 3.0 SDK and I am glad that the audio issue has been resolved. By "voice is audible after 8-15 seconds" did you mean that you could only hear the voice after calling the `TwilioVoice.connect()` method or after you received the `callDidConnect:` callback?
Please also provide SDK log with `TVOLogLevelTrace` level so we can take a look at some potential problem. I have a suspicion that it's taking significant amount of time to establish the signaling connection.

-bobie

**Comment by bchen-twilio** [comment]
Hi @outlookamusements 

Glad to know that the call is working for you now.
what are the actions performed on `B`'s side? especially the `verify the call to press any key` part. Are you using the `[TVOCall sendDigits:]` method on Customer B's call?

-bobie

**Comment by outlookamusements** [comment]
hi @bchen-twilio 

Yes, to verify the call press any key part i am using the `[TVOCall sendDigits:]` method on Customer B's call.

Thanks

**Comment by bchen-twilio** [comment]
Hi @outlookamusements 

Can you share a Call SID of the above scenario? The TwiML of the call will help us identify the problem you are experiencing.

Thanks.
-bobie

**Comment by piyushtank** [comment]
Closing an old ticket. Feel free to re-open if you run into the same issue or have any questions.
